### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by karlhorky**
### Affected Language Features

--

### Additional Info

Fixes some typos in the readme

### CODE REVIEW

**Comment by Viijay-Kr** [comment]
Thanks for this @karlhorky

**Review by Viijay-Kr — APPROVED** [review]

**Comment by Viijay-Kr** [comment]
Hey @karlhorky since you are a collaborator in this project, if you don't mind feel free to open PRs directly on to main (without fork)

I can't seem to know why the actions won't trigger on PRs from forks do you have any idea ?

**Comment by Viijay-Kr** [comment]
If you rebase it should run the checks. 

@karlhorky you might have to update the version number to publish a new version to market place it can be a minor one

**Comment by karlhorky** [comment]
Oh sorry rebased now!

I just did this during a lecture to show how to fork and do a pull request - sorry for not following the process from the same repo! I will try to remember this for next time.

**Comment by Viijay-Kr** [comment]
> Oh sorry rebased now!
> 
> I just did this during a lecture to show how to fork and do a pull request - sorry for not following the process from the same repo! I will try to remember this for next time.

No worries at all , now the PR checks works , if you don't mind could you update the version number in `package.json` so that a new release is published to market place

**Comment by karlhorky** [comment]
Bumped patch version 👍

**Comment by Viijay-Kr** [comment]
Thanks @karlhorky Appreciate it

**Comment by karlhorky** [comment]
Glad to help, thanks for the review and merge!

**Pull request merged**
