### PR TITLE
Add support for (SCSS) suffix selectors starting with &__ (used by BEM)

### PR DESCRIPTION
**Pull request by fundevstuff**
Add support for (SCSS) suffix selectors starting with &__ (used by BEM)

### CODE REVIEW

**Review by JohanMouchet — APPROVED** [review]
Pretty straightforward 👍

**Comment by JohanMouchet** [comment]
Thinking about it, I'm wondering if it's necessary to specify the character following the `&`.

Might it be more generic to use:
```
- selector.startsWith("&-") || selector.startsWith("&_")
+ selector.startsWith("&")
```

**Comment by Viijay-Kr** [comment]
@fundevstuff thanks for the PR , could you update the version in package.json . It's a minor update so a minor version should be enough. I currently don't have automatic version updates. So kindly bear with me :)

**Review by Viijay-Kr — APPROVED** [review]
Looks good

**Comment by fundevstuff** [comment]
> @fundevstuff thanks for the PR , could you update the version in package.json . It's a minor update so a minor version should be enough. I currently don't have automatic version updates. So kindly bear with me :)

Sure, np, pushed the version update 👍

**Comment by Viijay-Kr** [comment]
@fundevstuff I was wondering why the tests would fail on Mac and Windows . Turns out its a dependency issue which I shall resolve in a future PR. I will merge this one now

I am also thinking of introducing changesets to make this process easier in the future as far as version updates are concerned. Thanks again for your contribution

**Pull request merged**
